spring:
  application:
    name: LearnProject
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
  datasource:
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=animals}